export const DEFAULT_BG = "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=2000";

export const STARTER_TEMPLATE = [
  {
    "id": "cover-card",
    "type": "card",
    "x": 0,
    "y": 0,
    "width": 500,
    "height": 700,
    "isGlass": true,
    "bgColor": "rgba(0, 0, 0, 0.5)",
    "parentId": null
  },
  {
    "id": "cover-title-1",
    "type": "text",
    "content": "Anirudh",
    "x": 0,
    "y": 180,
    "fontSize": 96,
    "color": "#f8f0dc",
    "font": "Great Vibes",
    "width": 500,
    "parentId": "cover-card"
  },
  {
    "id": "cover-amp",
    "type": "text",
    "content": "&",
    "x": 0,
    "y": 280,
    "fontSize": 48,
    "color": "#d4af37",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "cover-card"
  },
  {
    "id": "cover-title-2",
    "type": "text",
    "content": "Akhila",
    "x": 0,
    "y": 320,
    "fontSize": 96,
    "color": "#f8f0dc",
    "font": "Great Vibes",
    "width": 500,
    "parentId": "cover-card"
  },
  {
    "id": "cover-date",
    "type": "text",
    "content": "20 MAY 2026",
    "x": 0,
    "y": 500,
    "fontSize": 20,
    "color": "#ffffff",
    "font": "Outfit",
    "width": 500,
    "parentId": "cover-card"
  },
  {
    "id": "cover-loc",
    "type": "text",
    "content": "CALICUT",
    "x": 0,
    "y": 540,
    "fontSize": 16,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "cover-card"
  },
  {
    "id": "invite-card",
    "type": "card",
    "x": 0,
    "y": 800,
    "width": 500,
    "height": 600,
    "isGlass": true,
    "bgColor": "rgba(0, 0, 0, 0.6)",
    "parentId": null
  },
  {
    "id": "invite-ornament-1",
    "type": "text",
    "content": "❀",
    "x": 0,
    "y": 50,
    "fontSize": 28,
    "color": "#d4af37",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-txt-1",
    "type": "text",
    "content": "Together with their families",
    "x": 0,
    "y": 100,
    "fontSize": 22,
    "color": "#e2e8f0",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-parent-1",
    "type": "text",
    "content": "Padmaja Vijayan",
    "x": 0,
    "y": 160,
    "fontSize": 20,
    "color": "#ffffff",
    "font": "Outfit",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-parent-2",
    "type": "text",
    "content": "& AB Vijayan Menon",
    "x": 0,
    "y": 200,
    "fontSize": 20,
    "color": "#ffffff",
    "font": "Outfit",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-req",
    "type": "text",
    "content": "request the honor of your presence\nat the marriage of",
    "x": 0,
    "y": 280,
    "fontSize": 18,
    "color": "#cbd5e1",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-n1",
    "type": "text",
    "content": "Anirudh",
    "x": 0,
    "y": 360,
    "fontSize": 64,
    "color": "#d4af37",
    "font": "Great Vibes",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-amp2",
    "type": "text",
    "content": "and",
    "x": 0,
    "y": 435,
    "fontSize": 24,
    "color": "#ffffff",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "invite-n2",
    "type": "text",
    "content": "Akhila",
    "x": 0,
    "y": 480,
    "fontSize": 64,
    "color": "#d4af37",
    "font": "Great Vibes",
    "width": 500,
    "parentId": "invite-card"
  },
  {
    "id": "ceremony-card",
    "type": "card",
    "x": 0,
    "y": 1500,
    "width": 500,
    "height": 550,
    "isGlass": true,
    "bgColor": "rgba(0, 0, 0, 0.6)",
    "parentId": null
  },
  {
    "id": "ceremony-title",
    "type": "text",
    "content": "Marriage Ceremony",
    "x": 0,
    "y": 80,
    "fontSize": 42,
    "color": "#f8f0dc",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "ceremony-div",
    "type": "text",
    "content": "❧ ────── ☙",
    "x": 0,
    "y": 140,
    "fontSize": 18,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "ceremony-date",
    "type": "text",
    "content": "MONDAY, 18 MAY 2026",
    "x": 0,
    "y": 200,
    "fontSize": 18,
    "color": "#ffffff",
    "font": "Outfit",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "ceremony-time",
    "type": "text",
    "content": "10:30 AM — 11:30 AM",
    "x": 0,
    "y": 250,
    "fontSize": 18,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "ceremony-venue",
    "type": "text",
    "content": "Poonthanam Auditorium",
    "x": 0,
    "y": 330,
    "fontSize": 24,
    "color": "#ffffff",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "ceremony-address",
    "type": "text",
    "content": "East Nada, Guruvayur",
    "x": 0,
    "y": 380,
    "fontSize": 16,
    "color": "#cbd5e1",
    "font": "Outfit",
    "width": 500,
    "parentId": "ceremony-card"
  },
  {
    "id": "reception-card",
    "type": "card",
    "x": 0,
    "y": 2150,
    "width": 500,
    "height": 550,
    "isGlass": true,
    "bgColor": "rgba(0, 0, 0, 0.6)",
    "parentId": null
  },
  {
    "id": "reception-title",
    "type": "text",
    "content": "Wedding Reception",
    "x": 0,
    "y": 80,
    "fontSize": 42,
    "color": "#f8f0dc",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "reception-div",
    "type": "text",
    "content": "❧ ────── ☙",
    "x": 0,
    "y": 140,
    "fontSize": 18,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "reception-date",
    "type": "text",
    "content": "WEDNESDAY, 20 MAY 2026",
    "x": 0,
    "y": 200,
    "fontSize": 18,
    "color": "#ffffff",
    "font": "Outfit",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "reception-time",
    "type": "text",
    "content": "05:00 PM — 09:00 PM",
    "x": 0,
    "y": 250,
    "fontSize": 18,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "reception-venue",
    "type": "text",
    "content": "Classic Auditorium (Majestic)",
    "x": 0,
    "y": 330,
    "fontSize": 24,
    "color": "#ffffff",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "reception-address",
    "type": "text",
    "content": "Palayam, Calicut",
    "x": 0,
    "y": 380,
    "fontSize": 16,
    "color": "#cbd5e1",
    "font": "Outfit",
    "width": 500,
    "parentId": "reception-card"
  },
  {
    "id": "moments-card",
    "type": "card",
    "x": 0,
    "y": 2800,
    "width": 500,
    "height": 400,
    "isGlass": true,
    "bgColor": "rgba(0, 0, 0, 0.6)",
    "parentId": null
  },
  {
    "id": "moments-title",
    "type": "text",
    "content": "Engagement Moments",
    "x": 0,
    "y": 60,
    "fontSize": 38,
    "color": "#f8f0dc",
    "font": "Cormorant Garamond",
    "width": 500,
    "parentId": "moments-card"
  },
  {
    "id": "moments-div",
    "type": "text",
    "content": "❧ ────── ☙",
    "x": 0,
    "y": 120,
    "fontSize": 18,
    "color": "#d4af37",
    "font": "Outfit",
    "width": 500,
    "parentId": "moments-card"
  },
  {
    "id": "moments-img-1",
    "type": "image",
    "imageUrl": "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=400",
    "x": 50,
    "y": 180,
    "width": 400,
    "height": 180,
    "parentId": "moments-card"
  }
];
